
ETFs_Data= [
    {"nombre": "AZ China", "ticker": "AZCN", "descripcion": "ETF que sigue el desempeño de las empresas más grandes de China."},
    {"nombre": "AZ Brasil", "ticker": "AZBR", "descripcion": "ETF que invierte en las principales empresas brasileñas."},
    {"nombre": "AZ BRIC", "ticker": "AZBRIC", "descripcion": "ETF que cubre mercados emergentes BRIC (Brasil, Rusia, India, China)."},
    {"nombre": "AZ Mercados Emergentes", "ticker": "AZEM", "descripcion": "ETF que rastrea los mercados emergentes globales."},
    {"nombre": "AZ Oro", "ticker": "AZGOLD", "descripcion": "ETF que replica el precio del oro en los mercados internacionales."},
    {"nombre": "AZ MSCI ASIA EX-JAPAN", "ticker": "AZASIA", "descripcion": "ETF que invierte en acciones asiáticas excluyendo Japón."},
    {"nombre": "AZ MSCI ACWI INDEX FUND", "ticker": "AZACWI", "descripcion": "ETF global que sigue el índice de mercados ACWI."},
    {"nombre": "AZ MSCI HONG KONG INDEX", "ticker": "AZHK", "descripcion": "ETF centrado en el mercado de Hong Kong."},
    {"nombre": "AZ MSCI JAPAN INDEX FD", "ticker": "AZJP", "descripcion": "ETF que rastrea las empresas más grandes de Japón."},
    {"nombre": "AZ MSCI FRANCE INDEX FD", "ticker": "AZFR", "descripcion": "ETF basado en el mercado francés."},
    {"nombre": "AZ MSCI AUSTRALIA INDEX", "ticker": "AZAU", "descripcion": "ETF enfocado en las principales empresas de Australia."},
    {"nombre": "AZ MSCI CANADA", "ticker": "AZCA", "descripcion": "ETF que cubre el mercado de acciones canadienses."},
    {"nombre": "AZ MSCI GERMANY INDEX", "ticker": "AZDE", "descripcion": "ETF que sigue las empresas alemanas más grandes."},
    {"nombre": "AZ MSCI TAIWAN INDEX FD", "ticker": "AZTW", "descripcion": "ETF enfocado en el mercado de Taiwán."},
    {"nombre": "AZ MSCI UNITED KINGDOM", "ticker": "AZUK", "descripcion": "ETF que rastrea empresas del Reino Unido."},
    {"nombre": "AZ MSCI SOUTH KOREA IND", "ticker": "AZKR", "descripcion": "ETF que sigue el mercado de Corea del Sur."},
    {"nombre": "AZ MSCI EMU", "ticker": "AZEMU", "descripcion": "ETF que cubre la Eurozona (EMU)."},
    {"nombre": "AZ LATIXX MEX CETETRAC", "ticker": "AZCETE", "descripcion": "ETF basado en los bonos CETETRAC en México."},
    {"nombre": "AZ LATIXX MEX M10TRAC", "ticker": "AZM10", "descripcion": "ETF que replica el bono mexicano M10."},
    {"nombre": "AZ LATIXX MEXICO M5TRAC", "ticker": "AZM5", "descripcion": "ETF basado en bonos a corto plazo del gobierno mexicano."},
    {"nombre": "AZ LATIXX MEX UDITRAC", "ticker": "AZUDI", "descripcion": "ETF que rastrea bonos UDI en México."},
    {"nombre": "AZ BG EUR GOVT BOND 1-3", "ticker": "AZEUR", "descripcion": "ETF de bonos gubernamentales europeos a corto plazo."},
    {"nombre": "AZ DJ US OIL & GAS EXPL", "ticker": "AZOIL", "descripcion": "ETF que invierte en el sector de exploración de petróleo y gas en EE.UU."},
    {"nombre": "AZ IPC LARGE CAP T R TR", "ticker": "AZIPC", "descripcion": "ETF basado en grandes empresas mexicanas del IPC."},
    {"nombre": "AZ S&P LATIN AMERICA 40", "ticker": "AZLATAM", "descripcion": "ETF de las 40 principales empresas de América Latina."},
    {"nombre": "AZ DJ US HOME CONSTRUCT", "ticker": "AZHOME", "descripcion": "ETF centrado en el sector de la construcción de viviendas en EE.UU."},
    {"nombre": "AZ RUSSELL 2000", "ticker": "AZR2000", "descripcion": "ETF que rastrea el índice de pequeñas capitalizaciones Russell 2000."},
    {"nombre": "AZ DJ US FINANCIAL SECT", "ticker": "AZFIN", "descripcion": "ETF que invierte en el sector financiero de EE.UU."},
    {"nombre": "AZ BARCLAYS AGGREGATE", "ticker": "AZAGG", "descripcion": "ETF que replica el índice de bonos Barclays Aggregate."},
    {"nombre": "AZ FTSE/XINHUA CHINA 25", "ticker": "AZCH25", "descripcion": "ETF que sigue a las 25 empresas más grandes de China."},
    {"nombre": "AZ QQQ NASDAQ 100", "ticker": "AZQQQ", "descripcion": "ETF que sigue el rendimiento del índice NASDAQ 100."},
    {"nombre": "AZ BARCLAYS 1-3 YEAR TR", "ticker": "AZB13", "descripcion": "ETF basado en bonos de corto plazo de Barclays."},
    {"nombre": "AZ SILVER TRUST", "ticker": "AZSLV", "descripcion": "ETF que replica el precio de la plata."},
    {"nombre": "AZ SPDR S&P 500 ETF TRUST", "ticker": "AZSPY", "descripcion": "ETF que sigue el índice S&P 500."},
    {"nombre": "AZ SPDR DJIA TRUST", "ticker": "AZDIA", "descripcion": "ETF basado en el índice Dow Jones Industrial Average."},
    {"nombre": "AZ VANGUARD EMERGING MARKET ETF", "ticker": "AZVEM", "descripcion": "ETF que invierte en mercados emergentes."},
    {"nombre": "AZ FINANCIAL SELECT SECTOR SPDR", "ticker": "AZXLF", "descripcion": "ETF que sigue el sector financiero del S&P 500."},
    {"nombre": "AZ HEALTH CARE SELECT SECTOR", "ticker": "AZXLV", "descripcion": "ETF que invierte en el sector salud del S&P 500."},
]

